<a href="https://colab.research.google.com/github/sruthi-analyst/sruthi-codeboosters-2026/blob/main/Day3/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install requests --quiet
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print('All libraries imported successfully')
print(f'pandas: {pd.__version__}')
print(f'requests: {requests.__version__}')

All libraries imported successfully
pandas: 2.2.2
requests: 2.32.4

In [4]:
raw_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/messy_sales_data.csv")

print(f'Raw data loaded: {raw_df.shape[0]} rows, {raw_df.shape[1]}columns')
print(f'Columns: {raw_df.columns.tolist()}')
print("\n First 5 rows: ")
print(raw_df.head().to_string(index=False))

Raw data loaded: 30 rows, 9columns
Columns: ['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']

 First 5 rows:
 order_id customer_name  product    category  quantity  unit_price order_date      city   sales_rep
     1001  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma
     1002    Priya Nair      NaN Electronics       1.0       15000 2024-01-07     Delhi  Sunita Rao
     1003    AMIT VERMA Keyboard Accessories       3.0        1200 2024-01-08 Bangalore Anil Sharma
     1004  Sunita Patel  Monitor Electronics       NaN       22000 2024-01-10   Chennai  Ravi Kumar
     1005  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma

In [5]:
print('='*55)
print('DATA QUALITY DOAGNOSIS REPORT')
print('='*55)

#1. MISSING VALUES
print("\n[1] MISSING VALUES per column:")
print(raw_df.isna().sum())

#2. DUPLICATES
print("\n[2] DUPLICATES:", raw_df.duplicated().sum())
# duplicates assigns number 1 only to the second occrance of thta value, and not the first occurance- it only accounts for the duplicate rows

#3. DATA TYPES
print("\n[3] DATA TYPES: ")
print(raw_df.dtypes)

#4. Unique Values in text columns (spot inconsistencies)
print("\n[4] UNIQUE CATAGORIES: ", raw_df['category'].unique())
print("[4] Sample Customer Names", raw_df['customer_name'].dropna().unique()[:8])
print("[4] Sample order_date values: ", raw_df['order_date'].dropna().unique()[:8])

=======================================================
DATA QUALITY DOAGNOSIS REPORT
=======================================================

[1] MISSING VALUES per column:
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

[2] DUPLICATES: 0

[3] DATA TYPES:
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

[4] UNIQUE CATAGORIES:  ['Electronics' 'Accessories' nan]
[4] Sample Customer Names ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']
[4] Sample order_date values:  ['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12' '2024-01-13' '2024-01-15']

In [6]:
print("[5] Missing values in quantity: ", raw_df['quantity'].isna().sum())

[5] Missing values in quantity:  3

In [77]:
print('='*55)
print('CREATE A WORKING COPY (ETL Best Practice)')
print('='*55)

df = raw_df.copy()

print(f"Working copy created: {df.shape}")
print('raw_df is untouched - we can always reset by running df = raw_df.copy()')

=======================================================
CREATE A WORKING COPY (ETL Best Practice)
=======================================================
Working copy created: (30, 9)
raw_df is untouched - we can always reset by running df = raw_df.copy()

In [78]:
print('='*55)
print('Fix #1: Handle Missing Values')
print('='*55)

print("Before handling nulls:\t", df.isnull().sum().sum(), "total missing values")

print("\nNo. of null values in Custome Name: ", df['customer_name'].isnull().sum())
df['customer_name'].fillna('Unknown Customer', inplace=True)
print("Null values of 'customer_name' columns handled successfully! ")
print("No. of null values in Custome Name: ", df['customer_name'].isnull().sum())


print("\nNo. of null values in quantity: ", df['quantity'].isnull().sum())
median_qty = df['quantity'].median()
df['quantity'].fillna(median_qty, inplace=True)
print("Null values of 'quantity' columns handled successfully! ")
print("No. of null values in quantity: ", df['quantity'].isnull().sum())


print("\nNo. of null values in category: ", df['category'].isnull().sum())
df['category'].fillna('uncategorised', inplace=True)
print("Null values of 'category' columns handled successfully! ")
print("No. of null values in category: ", df['category'].isnull().sum())


print("\nNo. of null values in product: ", df['product'].isnull().sum())
df['product'].fillna('Unknown Product', inplace=True)
print("Null values of 'product' columns handled successfully! ")
print("No. of null values in product: ", df['product'].isnull().sum())

print("\nAfter handling nulls:\t", df.isnull().sum().sum(), "total missing values")

=======================================================
Fix #1: Handle Missing Values
=======================================================
Before handling nulls:	 7 total missing values

No. of null values in Custome Name:  2
Null values of 'customer_name' columns handled successfully!
No. of null values in Custome Name:  0

No. of null values in quantity:  3
Null values of 'quantity' columns handled successfully!
No. of null values in quantity:  0

No. of null values in category:  1
Null values of 'category' columns handled successfully!
No. of null values in category:  0

No. of null values in product:  1
Null values of 'product' columns handled successfully!
No. of null values in product:  0

After handling nulls:	 0 total missing values

In [79]:
#Adding duplicate values to df
duplicate_row1 = df.iloc[3].copy()
duplicate_row2 = df.iloc[6].copy()
duplicate_row3 = df.iloc[18].copy()
df = pd.concat([df, pd.DataFrame([duplicate_row1])], ignore_index=True)
df = pd.concat([df, pd.DataFrame([duplicate_row2])], ignore_index=True)
df = pd.concat([df, pd.DataFrame([duplicate_row3])], ignore_index=True)

duplicate_rows = df[df.duplicated(keep=False)]
print(f"Found {len(duplicate_rows)} rows that are duplicates:\n")
display(duplicate_rows)

print(df.duplicated().sum(), "duplicate rows")

Found 6 rows that are duplicates:

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-01-10,Chennai,Ravi Kumar
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar
30,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-01-10,Chennai,Ravi Kumar
31,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
32,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar

3 duplicate rows

In [80]:
print('='*55)
print('Fix #2: Handle Duplicate Values')
print('='*55)

print("Before handling duplicates:\t", df.duplicated().sum(), "duplicate rows")
df.drop_duplicates(inplace=True)
print("After handling duplicates:\t", df.duplicated().sum(), "duplicate rows")

=======================================================
Fix #2: Handle Duplicate Values
=======================================================
Before handling duplicates:	 3 duplicate rows
After handling duplicates:	 0 duplicate rows

In [81]:
print('='*55)
print('Fix #3: Parsing')
print('='*55)

print('Sample dates before parsing: ')
print(df['order_date'].head(8).to_list())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=True, # This helps with 'DD-MM-YYYY' when month and day could be swapped
    format='mixed', # This will correctly parse both 'DD-MM-YYYY' and 'YYYY-MM-DD' by inferring for each element
    errors='coerce'
)

nat_count = df['order_date'].isnull().sum()
print(f'\nUnparseable data (NaT): {nat_count}')

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['date_name'] = df['order_date'].dt.strftime('%A')  # or dt.day_name()
df['month_name'] = df['order_date'].dt.strftime('%B') # or dt.month_name()

print('\nSample dates after parsing: ')
print(df[['order_date', 'year', 'month', 'month_name', 'date_name']].head(8))

df['order_date_formatted'] = df['order_date'].dt.strftime('%d-%m-%Y')
print('\nSample dates in new format:')
print(df[['order_date', 'order_date_formatted']].head(8))

=======================================================
Fix #3: Parsing
=======================================================
Sample dates before parsing:
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']

Unparseable data (NaT): 0

Sample dates after parsing:
  order_date  year  month month_name  date_name
0 2024-01-05  2024      1    January     Friday
1 2024-01-07  2024      1    January     Sunday
2 2024-01-08  2024      1    January     Monday
3 2024-01-10  2024      1    January  Wednesday
4 2024-01-05  2024      1    January     Friday
5 2024-01-07  2024      1    January     Sunday
6 2024-01-12  2024      1    January     Friday
7 2024-01-13  2024      1    January   Saturday

Sample dates in new format:
  order_date order_date_formatted
0 2024-01-05           05-01-2024
1 2024-01-07           07-01-2024
2 2024-01-08           08-01-2024
3 2024-01-10           10-01-2024
4 2024-01-05           05-01-2024
5 2024-01-07           07-01-2024
6 2024-01-12           12-01-2024
7 2024-01-13           13-01-2024

In [82]:
print('='*55)
print('Fix #4 & #5: Text standardisation and wrong category')
print('='*55)

print('Before standardisation: ', df['customer_name'].unique()[:6])
df['customer_name']=df['customer_name'].str.strip().str.title()
print('After standardisation: ', df['customer_name'].unique()[:6])

mask = (df['product']=='Keyboard') & (df['category']=='Electronics')
df.loc[mask, 'category'] = 'Computer Accessories'
print(df[['product', 'category']])

=======================================================
Fix #4 & #5: Text standardisation and wrong category
=======================================================
Before standardisation:  ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh']
After standardisation:  ['Ramesh Kumar' 'Priya Nair' 'Amit Verma' 'Sunita Patel' 'Kiran Mehta'
 'Deepak Singh']
            product              category
0            Laptop           Electronics
1   Unknown Product           Electronics
2          Keyboard           Accessories
3           Monitor           Electronics
4            Laptop           Electronics
5             Mouse           Accessories
6        Headphones           Electronics
7            Webcam           Accessories
8            Laptop           Electronics
9          Keyboard           Accessories
10          Monitor           Electronics
11          USB Hub           Accessories
12           Laptop           Electronics
13       Headphones           Electronics
14           Webcam           Accessories
15            Mouse           Accessories
16         Keyboard           Accessories
17          Monitor           Electronics
18           Laptop           Electronics
19          USB Hub           Accessories
20       Headphones           Electronics
21           Webcam           Accessories
22           Laptop           Electronics
23         Keyboard  Computer Accessories
24            Mouse           Accessories
25       Headphones           Electronics
26          Monitor         uncategorised
27           Laptop           Electronics
28          USB Hub           Accessories
29           Webcam           Accessories

In [83]:
print('='*55)
print('Fix #6: Fix Data Type + Create Revenue Column')
print('='*55)

df['revenue'] = (df['quantity'] * df['unit_price']).astype(int)
print(df[['customer_name', 'product', 'quantity', 'unit_price', 'revenue']].head())

print(f"\nTotal Revenue across all orders: ₹{df['revenue'].sum()}")

=======================================================
Fix #6: Fix Data Type + Create Revenue Column
=======================================================
  customer_name          product  quantity  unit_price  revenue
0  Ramesh Kumar           Laptop       2.0       45000    90000
1    Priya Nair  Unknown Product       1.0       15000    15000
2    Amit Verma         Keyboard       3.0        1200     3600
3  Sunita Patel          Monitor       2.0       22000    44000
4  Ramesh Kumar           Laptop       2.0       45000    90000

Total Revenue across all orders: ₹818000

In [84]:
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep,year,month,date_name,month_name,order_date_formatted,revenue
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,2024,1,Friday,January,05-01-2024,90000
1,1002,Priya Nair,Unknown Product,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao,2024,1,Sunday,January,07-01-2024,15000
2,1003,Amit Verma,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma,2024,1,Monday,January,08-01-2024,3600
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-01-10,Chennai,Ravi Kumar,2024,1,Wednesday,January,10-01-2024,44000
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,2024,1,Friday,January,05-01-2024,90000
5,1006,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao,2024,1,Sunday,January,07-01-2024,8000
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar,2024,1,Friday,January,12-01-2024,7000
7,1008,Unknown Customer,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma,2024,1,Saturday,January,13-01-2024,2500
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao,2024,1,Monday,January,15-01-2024,45000
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar,2024,1,Monday,January,15-01-2024,6000
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,2024-01-18,Delhi,Anil Sharma,2024,1,Thursday,January,18-01-2024,44000
11,1012,Suresh Rao,USB Hub,Accessories,8.0,600,2024-01-20,Bangalore,Sunita Rao,2024,1,Saturday,January,20-01-2024,4800
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,2024-01-22,Pune,Ravi Kumar,2024,1,Monday,January,22-01-2024,90000
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,2024-01-21,Kochi,Anil Sharma,2024,1,Sunday,January,21-01-2024,10500
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,2024-01-25,Surat,Sunita Rao,2024,1,Thursday,January,25-01-2024,5000
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao,2024,1,Sunday,January,07-01-2024,8000
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,2024-01-28,Hyderabad,Ravi Kumar,2024,1,Sunday,January,28-01-2024,6000
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,2024-01-30,Delhi,Anil Sharma,2024,1,Tuesday,January,30-01-2024,22000
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar,2024,2,Thursday,February,01-02-2024,45000
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-02-03,Lucknow,Sunita Rao,2024,2,Saturday,February,03-02-2024,9000
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-02-05,Chandigarh,Anil Sharma,2024,2,Monday,February,05-02-2024,7000
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-02-07,Bhopal,Ravi Kumar,2024,2,Wednesday,February,07-02-2024,7500
22,1023,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao,2024,1,Monday,January,15-01-2024,45000
23,1024,Preeti Saxena,Keyboard,Computer Accessories,4.0,1200,2024-02-10,Kanpur,Anil Sharma,2024,2,Saturday,February,10-02-2024,4800
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-02-12,Kolkata,Sunita Rao,2024,2,Monday,February,12-02-2024,4800
25,1026,Unknown Customer,Headphones,Electronics,1.0,3500,2024-02-14,Mumbai,Ravi Kumar,2024,2,Wednesday,February,14-02-2024,3500
26,1027,Rekha Nair,Monitor,uncategorised,2.0,22000,2024-02-15,Kochi,Anil Sharma,2024,2,Thursday,February,15-02-2024,44000
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar,2024,2,Sunday,February,18-02-2024,135000
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,2024-02-20,Allahabad,Sunita Rao,2024,2,Tuesday,February,20-02-2024,6000
29,1030,Kavya Nambiar,Webcam,Accessories,2.0,2500,2024-02-22,Thrissur,Anil Sharma,2024,2,Thursday,February,22-02-2024,5000

In [85]:
print('(❁´◡`❁)   '*6)
print('\t\t POST-CLEANING VALIDATION REPORT')
print(  '*'*60)

print(f'\nOriginal rows\t:\t{len(raw_df)}')
print(f'Cleaned rows\t:\t{len(df)}')
print(f'Rows Removed\t:\t{len(raw_df)-len(df)} (duplicates)')
total_missing_values = df.isnull().sum().sum()
print(f'Missing Values\t:\t{total_missing_values}')
total_duplicates = df.duplicated().sum()
print(f'Duplicates\t:\t{total_duplicates}')
total_date_nulls = df['order_date'].isnull().sum()
print(f'Date Nulls\t:\t{total_date_nulls}')
total_revenue_nulls = df['revenue'].isnull().sum()
print(f'Revenue NaN\t:\t{total_revenue_nulls}')
print(f'Categories\t:\t{sorted(df['category'].unique())}\n')
all_clean = (total_missing_values == 0) & (total_duplicates == 0) & (total_date_nulls == 0) & (total_revenue_nulls == 0)
print(f'\n{'~'*60}')
print(f'\nDATA IS CLEAN   :   {all_clean}')

(❁´◡`❁)   (❁´◡`❁)   (❁´◡`❁)   (❁´◡`❁)   (❁´◡`❁)   (❁´◡`❁)
		 POST-CLEANING VALIDATION REPORT
************************************************************

Original rows	:	30
Cleaned rows	:	30
Rows Removed	:	0 (duplicates)
Missing Values	:	0
Duplicates	:	0
Date Nulls	:	0
Revenue NaN	:	0
Categories	:	['Accessories', 'Computer Accessories', 'Electronics', 'uncategorised']


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DATA IS CLEAN   :   True